import PC1 from "@/public/images/pc1.jpeg";
import PC2 from "@/public/images/pc2.jpeg";
import PC3 from "@/public/images/pc3.jpeg";

export const products = [
  {
    id: 1,
    type: "POC",
    image: PC2,
    name: "Product 1",
    description: "Description for Product 1",
    category: "gaming",
    price: 1000,
    specs: [
      {
        CPU: true,
        Model: "7600X",
        Nuclee: 8,
        GHZ: 5.6,
      },
      {
        GPU: true,
        Model: "4090X",
        VRAM: "12GB",
        GHZ: 5.6,
      },
      {
        RAM: true,
        Model: "5200 MHZ",
      },
    ],
    performance: [
      {
        Game: "Cyberpunk 2077",
        Settings: [
          { Quality: "Low", FPS: "90" },
          { Quality: "Medium", FPS: "60" },
          { Quality: "High", FPS: "45" },
        ],
      },
      {
        Game: "Red Dead Redemption 2",
        Settings: [
          { Quality: "Low", FPS: "100" },
          { Quality: "Medium", FPS: "70" },
          { Quality: "High", FPS: "50" },
        ],
      },
      {
        Game: "Call of Duty: Warzone",
        Settings: [
          { Quality: "Low", FPS: "120" },
          { Quality: "Medium", FPS: "90" },
          { Quality: "High", FPS: "70" },
        ],
      },
    ],
  },
  {
    id: 2,
    type: "Gaming PC",
    image: PC1,
    name: "Product 2",
    description: "Description for Product 2",
    price: 1500,
    category: "gaming",
  },
  {
    id: 3,
    type: "Workstation PC",
    image: PC2,
    name: "Product 3",
    description: "Description for Product 3",
    price: 2000,
    category: "gaming",
  },
  {
    id: 4,
    type: "POC",
    image: PC2,
    name: "Product 4",
    description: "Description for Product 4",
    price: 1200,
    category: "workstation",
  },
  {
    id: 5,
    type: "Gaming PC",
    image: PC1,
    name: "Product 5",
    description: "Description for Product 5",
    price: 1800,
    category: "proiectare",
  },
  {
    id: 6,
    type: "Workstation PC",
    image: PC2,
    name: "Product 6",
    description: "Description for Product 6",
    price: 2200,
    category: "proiectare",
  },
  {
    id: 7,
    type: "POC",
    image: PC3,
    name: "Product 7",
    description: "Description for Product 7",
    price: 1300,
    category: "workstation",
  },
  {
    id: 8,
    type: "Gaming PC",
    image: PC2,
    name: "Product 8",
    description: "Description for Product 8",
    price: 1700,
  },
  {
    id: 9,
    type: "Workstation PC",
    image: PC1,
    name: "Product 9",
    description: "Description for Product 9",
    price: 2400,
    category: "workstation",
  },
  {
    id: 10,
    type: "POC",
    image: PC3,
    name: "Product 10",
    description: "Description for Product 10",
    price: 1100,
  },
  {
    id: 11,
    type: "Gaming PC",
    image: PC3,
    name: "Product 11",
    description: "Description for Product 11",
    price: 1600,
  },
  {
    id: 12,
    type: "Workstation PC",
    image: PC2,
    name: "Product 12",
    description: "Description for Product 12",
    price: 2300,
    category: "workstation",
  },
  {
    id: 13,
    type: "POC",
    image: PC1,
    name: "Product 13",
    description: "Description for Product 13",
    price: 1400,
    category: "workstation",
  },
  {
    id: 14,
    type: "Gaming PC",
    image: PC2,
    name: "Product 14",
    description: "Description for Product 14",
    price: 1900,
    category: "proiectare",
  },
  {
    id: 15,
    type: "Workstation PC",
    image: PC3,
    name: "Product 15",
    description: "Description for Product 15",
    price: 2500,
  },
  {
    id: 16,
    type: "POC",
    image: PC3,
    name: "Product 16",
    description: "Description for Product 16",
    price: 1500,
    category: "proiectare",
  },
  {
    id: 17,
    type: "Gaming PC",
    image: PC1,
    name: "Product 17",
    description: "Description for Product 17",
    price: 2000,
  },
  {
    id: 18,
    type: "Workstation PC",
    image: PC2,
    name: "Product 18",
    description: "Description for Product 18",
    price: 2600,
  },
  {
    id: 19,
    type: "POC",
    image: PC1,
    name: "Product 19",
    description: "Description for Product 19",
    price: 1600,
  },
  {
    id: 20,
    type: "Gaming PC",
    image: PC2,
    name: "Product 20",
    description: "Description for Product 20",
    price: 2100,
  },
];
